auto: true
server: true
server_port: 5000
markdown: rdiscount
pygments: true
rdiscount:
  extensions: [smart]
exclude: [Makefile, README.md]

name: Collin Watson
url: http://collinwat.com
permalink: /:title
description: Personal space to share ideas and experiences
email: collinwat@gmail.com
twitter: collinwat
github: collinwat
gravatar_url: //www.gravatar.com/avatar/d3e5ad3f781c04194959fb88f092882a
google:
    analytics: UA-40055318-1
